(package "project-abbrev"
         "0.0.4"
         "Customize abbreviation expansion in the project")

(website-url "https://github.com/jcs-elpa/project-abbrev")
(keywords "abbreviation" "customizable" "shortcut")

(package-file "project-abbrev.el")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
